### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Jamaotaku** [Ivaan1990/Eduaction#1]
Хочу узнать цель задачи)

**Comment by Ivaan1990** [comment]
Так назвал, ничего уже тогда в голову не лезло))) в дальнейшем так не буду называть.
Вопрос собственно есть, класс ExampleArray, метод getSpiral, нужно чтобы элементы массива увеличивались по спирали...алгоритм пытаюсь надумать, но все никак) прошу помощи)))

**Comment by Ivaan1990** [comment]
Я сделал увеличение по спирали, класс ExampleTester, но жутко криво, и увеличивает как то не правильно.

**Comment by Ivaan1990** [comment]
Класс Example2Demo, задача была такая:
Создать программу, которая определяет,  что введено,  символ, цифра, или знак пунктуации.
По мне так, придраться не к чему)))

**Comment by Jamaotaku** [comment]
В целом, жду реализации спирального заполнения

**Comment by Ivaan1990** [comment]
Хорошо, сегодня надеюсь доделаю

**Comment by Ivaan1990** [comment]
Вообщем, первый ряд и последний столбец увеличивает правильно, а дальше ну никак не получается...
